**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

np.array([5, 15, 25, 35, 45])

array([ 5, 15, 25, 35, 45])

In [6]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.arange(10,19)

array([10, 11, 12, 13, 14, 15, 16, 17, 18])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [9]:
numpy_array = np.array([12, 24, 36, 48, 60])

In [11]:
array_1 = numpy_array * 2
array_1

array([ 24,  48,  72,  96, 120])

In [12]:
array_2 = numpy_array + 10
array_2

array([22, 34, 46, 58, 70])

In [13]:
array_3 = numpy_array ** 2
array_3

array([ 144,  576, 1296, 2304, 3600])

In [31]:
array_4 = np.std(numpy_array)
print(array_4)

16.97056274847714



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [17]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

In [30]:
print(np.mean(data))
print(np.min(data))
print(np.max(data))
print(np.sum(data))

45.42857142857143
18
79
318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [22]:
arr = np.array([15, 22, 35, 44, 58, 67])

In [27]:
print(arr[0])
print(arr[-1])
print(arr[1:3])

15
67
[22 35]


In [29]:
mask = arr > 40
arr[mask]

array([44, 58, 67])


---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [33]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [36]:
matrix.shape

(3, 3)

In [45]:
matrix[0:1]

array([[2, 4, 6]])

In [51]:
matrix[:,1]

array([ 4, 10, 16])

In [53]:
print(np.mean(matrix))

10.0


In [54]:
print(np.sum(matrix))

90
